steps:
  - name: "python"
    entrypoint: "bash"
    args:
      - "-lc"
      - |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pytest -q

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/microservices-exercise-3/flask/my-flask-app:latest"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/microservices-exercise-3/flask/my-flask-app:latest"

options:
  logging: CLOUD_LOGGING_ONLY